[package]
name = "guia"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0"
clap = "4.5"
inquire = "0.7"
walkdir = "2.5"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }

